const zodiacNames = [
  "Aries","Taurus", "Gemini","Cancer","Leo","Virgo","Libra","Scorpio","Sagittarius","Capricorn","Aquarius","Pisces"
];
const dobNature = [
    "Born leaders, confident, independent, and ambitious." ,
    "Emotional, caring, diplomatic, and peace-loving by nature." ,
  "Creative, expressive, optimistic, and socially active." ,
    "Practical, disciplined, hardworking, and systematic thinkers." ,
    "Adventurous, energetic, curious, and freedom-loving." ,
    "Loving, responsible, family-oriented, and artistic." ,
    "Spiritual, thoughtful, introverted, and deep thinkers." ,
    "Powerful, authoritative, goal-oriented, and disciplined." ,
    "Brave, humanitarian, emotional, and action-driven." ,
    "Natural leaders with strong willpower and confidence." ,
   "Highly intuitive, inspirational, sensitive, and visionary." ,
    "Creative, expressive, and adaptable with social charm." ,
  "Determined, hardworking, disciplined, and practical." ,
    "Energetic, intelligent, adaptable, but sometimes restless." ,
    "Charming, loving, attractive, and emotionally strong.",
    "Spiritual, analytical, reserved, and inward-focused.",
    "Ambitious, responsible, respected, and success-oriented.",
    "Emotional, compassionate, service-oriented, and intense.",
  "Independent, confident, authoritative, and self-reliant.",
    "Sensitive, calm, diplomatic, and emotionally balanced.",
    "Optimistic, lucky, creative, and socially popular.",
    "Master builder type: practical, visionary, and disciplined.",
    "Smart, expressive, quick learners with good communication.",
    "Caring, loyal, emotional, and family-focused." ,
    "Intelligent, curious, spiritual, and research-oriented." ,
    "Responsible, business-minded, and family-oriented." ,
    "Kind-hearted, humanitarian, wise, and emotionally deep." ,
    "Strong-willed, ambitious, independent, and bold." ,
    "Emotional, intuitive, artistic, and sensitive.",
    "Creative, expressive, optimistic, and charming." ,
    "Practical, disciplined, leadership-oriented, and self-made." 
];
const victimCardStatements = [
  "Often feels misunderstood and believes others are unfair to them.",
  "Tends to see themselves as the victim in most conflicts.",
  "Feels life has been harder on them than on others.",
  "Frequently seeks sympathy by highlighting personal struggles.",
  "Blames circumstances more than taking responsibility.",
  "Believes people do not recognize their efforts enough.",
  "Feels emotionally hurt easily and holds onto past pain.",
  "Often thinks others take advantage of their kindness.",
  "Sees problems as happening to them rather than because of choices.",
  "Feels ignored, neglected, or unappreciated by others.",
  "Uses emotional expression to gain understanding or support.",
  "Believes they give more than they receive in relationships.",
  "Often focuses on what went wrong instead of what can be fixed.",
  "Feels unlucky or repeatedly wronged by fate.",
  "Struggles to move on from perceived injustices.",
  "Feels others are responsible for their emotional state.",
  "Interprets criticism as personal attacks.",
  "Often expects others to understand their pain without explanation.",
  "Feels powerless in difficult situations.",
  "Tends to replay past hurts and unfair moments."
];
const dailyLifeTips = [
  "Wake up at a fixed time every day",
  "Drink a glass of water after waking up",
  "Do 10–15 minutes of exercise or stretching",
  "Get some sunlight in the morning",
  "Avoid checking your phone for the first 30 minutes",
  "Eat a healthy breakfast and don’t skip it",

  "Plan your day the night before",
  "Write 3 important tasks for the day",
  "Do difficult work when your mind is fresh",
  "Use the Pomodoro technique (25 minutes focus)",
  "Keep your workspace clean",
  "Learn something new every day",

  "Revise what you studied the same day",
  "Practice questions instead of only reading",
  "Improve one skill regularly",
  "Read books instead of endless scrolling",
  "Ask questions when you don’t understand",
  "Maintain notes properly",

  "Limit social media usage",
  "Keep your phone away while studying",
  "Use apps only if they add value",
  "Avoid multitasking",
  "Sleep on time (7–8 hours)",

  "Be grateful for small things",
  "Speak politely and listen more",
  "Help others whenever possible",
  "Control anger and pause before reacting",
  "Eat less junk food",
  "Spend time with family and friends",
  "Be consistent, not perfect"
];
const futurePredictions = [
  "Artificial Intelligence will become part of everyday life",
  "Remote work will be more common than office work",
  "Electric vehicles will replace most petrol vehicles",
  "Cashless transactions will dominate the economy",
  "Online education will grow faster than traditional classrooms",
  "Healthcare will become more technology-driven",
  "Renewable energy will overtake fossil fuels",
  "Smart homes will become a standard lifestyle",
  "Robots will assist humans in daily tasks",
  "Cybersecurity jobs will increase rapidly",
  "Space tourism will become affordable",
  "Digital currencies will be widely accepted",
  "Climate change policies will become stricter",
  "5G and future networks will transform communication",
  "Virtual reality will be used in education and training",
  "Automation will change job roles across industries",
  "Personal data protection will become more important",
  "Mental health awareness will increase globally",
  "Human–machine collaboration will grow stronger",
  "Lifelong learning will be necessary for everyone"
];


